parameters:
    bender.01:
        - FAUX
        - narmol
        - au fait
        - je vous ais pas dis
        - au kebab en bas
        - sinon
        - enfin
        - ce matin
        - hier
        - avant hier
        - y a 2h
        - lundi
        - mardi
        - mercredi
        - jeudi
        - vendredi
        - samedi
        - lundi derniers
        - mardi derniers
        - mercredi derniers
        - jeudi derniers
        - vendredi derniers
        - noel derniers
        - a paques
        - a canne
        - en france
        - en allemagne
        - en italie
        - au portugal
        - en roumanie
        - cet été
        - lhivers derniers
        - le printemps derniers
        - durant mes vacances à tourcoing
        - au camp de vacance du lavandoux
        - au theatre de bondy
        - a la salle polyvalente de creteil
        - a la mjc de saint denis
        - devant le franprix de chez ma maman
        - a sarcelles
        - hier soir
        - ce matin
        - en venant au taf
        - a clichy
