parameters:
    bender.01:
        - FAUX
        - narmol
        - au fait
        - je vous ais pas dis
        - au kebab en bas
        - sinon
        - enfin
        - ce matin
        - hier
        - avant hier
        - il y à 2h
        - lundi
        - mardi
        - mercredi
        - jeudi
        - vendredi
        - samedi
        - lundi derniers
        - mardi derniers
        - mercredi derniers
        - jeudi derniers
        - vendredi derniers
        - noel derniers
        - à paques
        - à canne
        - en France
        - en Allemagne
        - en Italie
        - au Portugal
        - en Roumanie
        - cet été
        - l'hivers derniers
        - le printemps derniers
        - durant mes vacances à tourcoing
        - au camp de vacance du lavandoux
        - au theatre de bondy
        - à la salle polyvalente de creteil
        - à la MJC de saint denis
        - devant le franprix de chez ma maman
        - à Sarcelles
        - hier soir
        - ce matin
        - en venant au taf
        - à Clichy
