parameters:
    bender.02:
        - j'ai
        - ma mére a
        - mon chien a
        - ma tante a
        - mon oncle a
        - ma soeur a
        - la mére de mon cousin a
        - la soeur de ma mére a
