parameters:
    bender.03:
        - collé
        - trouvé
        - mangé
        - chié
        - reçus
        - changé
        - modifié
        - acheté
        - passé
        - vendus
        - caché
        - tué
        - écrasé
        - craché
        - déplacé
        - déménagé
        - detruis
        - découpé
        - vendu
        - parlé avec
        - discuté avec
        - fait du biz avec
        - courru vers
        - attrapé
        - nettoyé
        - soufflé
        - interrogé
        - répondus à
        - ouvert
        - mis dans
        - matté
        - baisé
