parameters:
    bender.jcvd:
        - à clichy
        - au theatre de bondy
        - à l'olympia
        - au point virgule
        - a villetaneuse
        - dans le 12em
        - à chatelet
        - à paris
        - au palais des glaces
        - à eurodisney
        - à bercy
        - à la villette
        - à porte de montreuil
        - à porte de champeret
        - à goussainville
        - entre luzarche et sainte marie des bois
        - pas loin de chez ma mére a ecouen
        - à lille
        - à lyon
        - chez micheline a 5 minutes du franprix de la porte maillot
        - à porte maillot
        - devant le franprix de luzarche
