parameters:
    bender.tv:
        - D8
        - Canal+
        - le journal de France3
        - le soir 3
        - France2
        - E=M6
        - M6
        - 7 à 8
        - Capital
        - Enquete exclusive
        - Camping paradise
        - On est pas couché
        - Le grand journal
        - Le petit journal
        - Le before de c+
        - TF1
        - NRJ12
        - France4
        - Les Anges
        - Les ch'tis
